# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReleases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='date released')),
            ],
        ),
        migrations.CreateModel(
            name='AccountReleaseServicePack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date installed')),
                ('accountReleaseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releasebot.AccountReleases')),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReleases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenkinsJobName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=1)),
                ('jenkinsContainer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Releases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=1)),
                ('type', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='date released')),
                ('releaseNotes', models.CharField(max_length=200)),
                ('technicalNotes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=1)),
                ('date', models.DateField(verbose_name='date installed')),
                ('productReleaseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releasebot.ProductReleases')),
            ],
        ),
        migrations.AddField(
            model_name='productreleases',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releasebot.Products'),
        ),
        migrations.AddField(
            model_name='productreleases',
            name='releaseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releasebot.Releases'),
        ),
        migrations.AddField(
            model_name='accountreleaseservicepack',
            name='servicePackId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releasebot.ServicePacks'),
        ),
        migrations.AddField(
            model_name='accountreleases',
            name='accountId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releasebot.Accounts'),
        ),
        migrations.AddField(
            model_name='accountreleases',
            name='productReleaseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releasebot.ProductReleases'),
        ),
    ]
